### ISSUE TITLE
Error, Invalid frame IO reading

### ISSUE THREAD

**Issue by kingkill315** [Taymindis/c-stomp#2]
I change the IP and PORT to my own activeMQ，I add some print
----------------------------------------------------------------------------------------------
Starting stomp connection, sending and consuming /amq/queue/stompqueue
i == 12,failed here
Error, Invalid frame IO reading
i == 12,failed here
Error, Invalid frame IO reading
disconnecting Stomp
Test Passed
------------------------------------------------------------------------------------------------
How to handle the mistake？
// port is not correct

**Comment by kingkill315** [comment]
it seems function cstmp_recv,Parse cmd failed

**Comment by Taymindis** [comment]
could you show me your sample code ?

**Comment by kingkill315** [comment]
> could you show me your sample code 
I mistook the  port , I have solved  the problem
in addtion,I want to know ,if I want to add groupID to header,how do I add related  key value ？

**Comment by Taymindis** [comment]
Is this not what you want? I am sorry i less maintaining this project anymore

```
   cstmp_add_header(fr, "groupID", "Your GroupID");
```
